import AppKit
import CryptoKit
import SwiftData

@MainActor
final class ClipboardMonitor {
    private let context: ModelContext
    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var timer: Timer?
    private let pollInterval: TimeInterval = 0.3

    init(context: ModelContext) {
        self.context = context
        self.lastChangeCount = NSPasteboard.general.changeCount
    }

    func start() {
        stop()
        timer = Timer.scheduledTimer(withTimeInterval: pollInterval, repeats: true) { [weak self] _ in
            Task { @MainActor in self?.tick() }
        }
        RunLoop.main.add(timer!, forMode: .common)
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func tick() {
        let cc = pasteboard.changeCount
        guard cc != lastChangeCount else { return }
        lastChangeCount = cc
        capture()
    }

    private func capture() {
        let types = pasteboard.types ?? []
        if types.contains(NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")) { return }
        if types.contains(NSPasteboard.PasteboardType("org.nspasteboard.TransientType")) { return }
        if types.contains(NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")) { return }
        if types.contains(NSPasteboard.PasteboardType("app.kaste.internal")) { return }

        let frontApp = NSWorkspace.shared.frontmostApplication
        let archive = serialize()

        // File URLs
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self]) as? [URL], !urls.isEmpty,
           urls.allSatisfy({ $0.isFileURL }) {
            let paths = urls.map { $0.path }
            let h = sha256(paths.joined(separator: "\n"))
            upsert(kind: .file, hash: h, archive: archive, frontApp: frontApp) {
                ClipItem(kind: .file, hash: h, plainText: paths.joined(separator: "\n"),
                         filePaths: paths, pasteboardArchive: archive,
                         sourceBundleID: frontApp?.bundleIdentifier,
                         sourceAppName: frontApp?.localizedName)
            }
            return
        }

        // Image
        if let img = NSImage(pasteboard: pasteboard),
           let tiff = img.tiffRepresentation,
           let rep = NSBitmapImageRep(data: tiff),
           let png = rep.representation(using: .png, properties: [:]) {
            let h = sha256(png)
            upsert(kind: .image, hash: h, archive: archive, frontApp: frontApp) {
                ClipItem(kind: .image, hash: h, plainText: nil, imageData: png,
                         pasteboardArchive: archive,
                         sourceBundleID: frontApp?.bundleIdentifier,
                         sourceAppName: frontApp?.localizedName)
            }
            return
        }

        // RTF
        if let rtf = pasteboard.data(forType: .rtf),
           let attr = try? NSAttributedString(data: rtf, options: [:], documentAttributes: nil) {
            let plain = attr.string
            let h = sha256(plain)
            upsert(kind: .rtf, hash: h, archive: archive, frontApp: frontApp) {
                ClipItem(kind: .rtf, hash: h, plainText: plain, rtfData: rtf,
                         pasteboardArchive: archive,
                         sourceBundleID: frontApp?.bundleIdentifier,
                         sourceAppName: frontApp?.localizedName)
            }
            return
        }

        // Plain text → detect URL / color
        if let str = pasteboard.string(forType: .string) {
            let trimmed = str.trimmingCharacters(in: .whitespacesAndNewlines)
            let h = sha256(str)
            var kind: ClipKind = .text
            var colorHex: String? = nil

            if let _ = URL(string: trimmed), trimmed.range(of: #"^https?://"#, options: .regularExpression) != nil {
                kind = .url
            } else if trimmed.range(of: #"^#?[0-9a-fA-F]{6}$"#, options: .regularExpression) != nil {
                kind = .color
                colorHex = trimmed.hasPrefix("#") ? trimmed : "#" + trimmed
            }

            upsert(kind: kind, hash: h, archive: archive, frontApp: frontApp) {
                ClipItem(kind: kind, hash: h, plainText: str, colorHex: colorHex,
                         pasteboardArchive: archive,
                         sourceBundleID: frontApp?.bundleIdentifier,
                         sourceAppName: frontApp?.localizedName)
            }
        }
    }

    private func upsert(
        kind: ClipKind, hash: String, archive: Data?,
        frontApp: NSRunningApplication?,
        make: () -> ClipItem
    ) {
        // We deliberately do NOT mutate an existing matching row here.
        // Touching properties on a row that the row cache thinks exists
        // but has actually been purged by retention/capacity cleanup will
        // crash inside Core Data's fault-fulfillment (_PFFaultHandlerLookupRow)
        // and Swift cannot catch that NSException → SIGABRT → mid-write SQLite
        // file gets truncated and the whole history vanishes on relaunch.
        //
        // Strategy: always insert a fresh row, then dedup in a separate task.
        // The dedup pass keeps the newest row per content hash, so the
        // visible behaviour is identical to "bump lastUsedAt" without the
        // dangerous in-place mutation.
        let item = make()
        context.insert(item)
        do {
            try context.save()
        } catch {
            NSLog("Kaste: ClipboardMonitor insert save failed: \(error)")
        }
        Task { @MainActor in
            self.deduplicate(hash: hash)
            self.enforceRetention()
            self.enforceCapacity()
        }
    }

    /// Collapse rows that share `contentHash`: keep the most recent (or any
    /// pinned), delete the rest. Safe to call repeatedly.
    private func deduplicate(hash: String) {
        let descriptor = FetchDescriptor<ClipItem>(
            predicate: #Predicate { $0.contentHash == hash },
            sortBy: [SortDescriptor(\.lastUsedAt, order: .reverse)]
        )
        guard let matches = (try? context.fetch(descriptor)), matches.count > 1 else { return }
        // Keep the newest non-deleted row, preserving any pinned ones.
        var kept = false
        for item in matches {
            if item.isPinned { continue }
            if !kept { kept = true; continue }
            context.delete(item)
        }
        do {
            try context.save()
        } catch {
            NSLog("Kaste: dedup save failed: \(error)")
        }
    }

    func backfillSearchKey() {
        let d = FetchDescriptor<ClipItem>(predicate: #Predicate { $0.searchKey == nil && $0.plainText != nil })
        guard let pending = try? context.fetch(d), !pending.isEmpty else { return }
        for item in pending { item.searchKey = item.plainText?.lowercased() }
        try? context.save()
    }

    func enforceRetention() {
        let days = UserDefaults.standard.object(forKey: "retentionDays") as? Int ?? 30
        guard days > 0 else { return }
        let cutoff = Date().addingTimeInterval(-Double(days) * 86400)
        let expired = FetchDescriptor<ClipItem>(
            predicate: #Predicate { !$0.isPinned && $0.lastUsedAt < cutoff }
        )
        guard let victims = try? context.fetch(expired), !victims.isEmpty else { return }
        for item in victims { context.delete(item) }
        try? context.save()
    }

    func enforceCapacity() {
        let maxItems = UserDefaults.standard.object(forKey: "maxItems") as? Int ?? 1000
        let nonPinned = FetchDescriptor<ClipItem>(predicate: #Predicate { !$0.isPinned })
        guard let total = try? context.fetchCount(nonPinned), total > maxItems else { return }
        var oldest = FetchDescriptor<ClipItem>(
            predicate: #Predicate { !$0.isPinned },
            sortBy: [SortDescriptor(\.lastUsedAt, order: .forward)]
        )
        oldest.fetchLimit = total - maxItems
        guard let victims = try? context.fetch(oldest) else { return }
        for item in victims { context.delete(item) }
        try? context.save()
    }

    private func serialize() -> Data? {
        guard let items = pasteboard.pasteboardItems else { return nil }
        var dict: [[String: Data]] = []
        for item in items {
            var entry: [String: Data] = [:]
            for type in item.types {
                if let data = item.data(forType: type) {
                    entry[type.rawValue] = data
                }
            }
            dict.append(entry)
        }
        return try? NSKeyedArchiver.archivedData(withRootObject: dict, requiringSecureCoding: false)
    }

    private func sha256(_ s: String) -> String { sha256(Data(s.utf8)) }
    private func sha256(_ data: Data) -> String {
        SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
    }
}
