import AppKit
import CryptoKit
import SwiftData

@MainActor
final class ClipboardMonitor {
    private let context: ModelContext
    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var timer: Timer?
    private let pollInterval: TimeInterval = 0.3
    private var cleanupPending = false

    init(context: ModelContext) {
        self.context = context
        self.lastChangeCount = NSPasteboard.general.changeCount
    }

    func start() {
        stop()
        // Timer fires on the current run loop (main). We're already @MainActor,
        // so hop straight into tick() — no extra Task hop that could reorder
        // ticks under load.
        timer = Timer.scheduledTimer(withTimeInterval: pollInterval, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.tick() }
        }
        RunLoop.main.add(timer!, forMode: .common)
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func tick() {
        let cc = pasteboard.changeCount
        guard cc != lastChangeCount else { return }
        lastChangeCount = cc
        capture()
    }

    private func capture() {
        let types = pasteboard.types ?? []
        if types.contains(NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")) { return }
        if types.contains(NSPasteboard.PasteboardType("org.nspasteboard.TransientType")) { return }
        if types.contains(NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")) { return }
        if types.contains(NSPasteboard.PasteboardType("app.kaste.internal")) { return }

        NSLog("Kaste: pasteboard types = \(types.map { $0.rawValue })")

        let frontApp = NSWorkspace.shared.frontmostApplication
        let archive = serialize()

        // File URLs
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self]) as? [URL], !urls.isEmpty,
           urls.allSatisfy({ $0.isFileURL }) {
            let paths = urls.map { $0.path }
            let h = sha256(paths.joined(separator: "\n"))
            upsert(kind: .file, hash: h, archive: archive, frontApp: frontApp) {
                ClipItem(kind: .file, hash: h, plainText: paths.joined(separator: "\n"),
                         filePaths: paths, pasteboardArchive: archive,
                         sourceBundleID: frontApp?.bundleIdentifier,
                         sourceAppName: frontApp?.localizedName)
            }
            return
        }

        // Image
        if let img = NSImage(pasteboard: pasteboard),
           let tiff = img.tiffRepresentation,
           let rep = NSBitmapImageRep(data: tiff),
           let png = rep.representation(using: .png, properties: [:]) {
            let h = sha256(png)
            upsert(kind: .image, hash: h, archive: archive, frontApp: frontApp) {
                ClipItem(kind: .image, hash: h, plainText: nil, imageData: png,
                         pasteboardArchive: archive,
                         sourceBundleID: frontApp?.bundleIdentifier,
                         sourceAppName: frontApp?.localizedName)
            }
            return
        }

        // HTML (or WebArchive) with an embedded base64 data-URI image.
        // Chrome extensions like FireShot / GoFullPage often only put this
        // representation on the pasteboard — no direct .png/.tiff.
        if let png = extractImagePNGFromRichPasteboard() {
            let h = sha256(png)
            upsert(kind: .image, hash: h, archive: archive, frontApp: frontApp) {
                ClipItem(kind: .image, hash: h, plainText: nil, imageData: png,
                         pasteboardArchive: archive,
                         sourceBundleID: frontApp?.bundleIdentifier,
                         sourceAppName: frontApp?.localizedName)
            }
            return
        }

        // RTF
        if let rtf = pasteboard.data(forType: .rtf),
           let attr = try? NSAttributedString(data: rtf, options: [:], documentAttributes: nil) {
            let plain = attr.string
            let h = sha256(plain)
            upsert(kind: .rtf, hash: h, archive: archive, frontApp: frontApp) {
                ClipItem(kind: .rtf, hash: h, plainText: plain, rtfData: rtf,
                         pasteboardArchive: archive,
                         sourceBundleID: frontApp?.bundleIdentifier,
                         sourceAppName: frontApp?.localizedName)
            }
            return
        }

        // Plain text → detect URL / color
        if let str = pasteboard.string(forType: .string) {
            let trimmed = str.trimmingCharacters(in: .whitespacesAndNewlines)
            let h = sha256(str)
            var kind: ClipKind = .text
            var colorHex: String? = nil

            if let _ = URL(string: trimmed), trimmed.range(of: #"^https?://"#, options: .regularExpression) != nil {
                kind = .url
            } else if trimmed.range(of: #"^#?[0-9a-fA-F]{6}$"#, options: .regularExpression) != nil {
                kind = .color
                colorHex = trimmed.hasPrefix("#") ? trimmed : "#" + trimmed
            }

            upsert(kind: kind, hash: h, archive: archive, frontApp: frontApp) {
                ClipItem(kind: kind, hash: h, plainText: str, colorHex: colorHex,
                         pasteboardArchive: archive,
                         sourceBundleID: frontApp?.bundleIdentifier,
                         sourceAppName: frontApp?.localizedName)
            }
        }
    }

    private func upsert(
        kind: ClipKind, hash: String, archive: Data?,
        frontApp: NSRunningApplication?,
        make: () -> ClipItem
    ) {
        // We deliberately do NOT mutate an existing matching row here.
        // Touching properties on a row that the row cache thinks exists
        // but has actually been purged by retention/capacity cleanup will
        // crash inside Core Data's fault-fulfillment (_PFFaultHandlerLookupRow)
        // and Swift cannot catch that NSException → SIGABRT → mid-write SQLite
        // file gets truncated and the whole history vanishes on relaunch.
        //
        // Strategy: always insert a fresh row, then dedup in a separate task.
        // The dedup pass keeps the newest row per content hash, so the
        // visible behaviour is identical to "bump lastUsedAt" without the
        // dangerous in-place mutation.
        let item = make()
        context.insert(item)
        do {
            try context.save()
        } catch {
            // Save failed — the context is now holding a dirty insert. Roll
            // back so we don't compound the problem on the next tick, and
            // snapshot the store on the way out so the user can at least
            // recover from the last-known-good state.
            NSLog("Kaste: ClipboardMonitor insert save failed: \(error) — rolling back")
            context.rollback()
            Task.detached(priority: .utility) {
                StoreManager.snapshotNow()
            }
            return
        }
        Task { @MainActor in
            self.deduplicate(hash: hash)
            self.scheduleCleanup()
        }
    }

    /// Coalesce enforceRetention + enforceCapacity into at most one run every
    /// 5 seconds. Repeated captures no longer trigger back-to-back deletions
    /// that could delete a ClipItem while ClipCardView is mid-read of its
    /// properties.
    private func scheduleCleanup() {
        guard !cleanupPending else { return }
        cleanupPending = true
        DispatchQueue.main.asyncAfter(deadline: .now() + 5) { [weak self] in
            guard let self else { return }
            self.cleanupPending = false
            self.enforceRetention()
            self.enforceCapacity()
        }
    }

    /// Collapse rows that share `contentHash`: keep the most recent (or any
    /// pinned), delete the rest. Safe to call repeatedly.
    private func deduplicate(hash: String) {
        let descriptor = FetchDescriptor<ClipItem>(
            predicate: #Predicate { $0.contentHash == hash },
            sortBy: [SortDescriptor(\.lastUsedAt, order: .reverse)]
        )
        guard let matches = (try? context.fetch(descriptor)), matches.count > 1 else { return }
        // Keep the newest non-deleted row, preserving any pinned ones.
        var kept = false
        for item in matches {
            if item.isPinned { continue }
            if !kept { kept = true; continue }
            context.delete(item)
        }
        do {
            try context.save()
        } catch {
            NSLog("Kaste: dedup save failed: \(error)")
        }
    }

    func backfillSearchKey() {
        let d = FetchDescriptor<ClipItem>(predicate: #Predicate { $0.searchKey == nil && $0.plainText != nil })
        let pending: [ClipItem]
        do { pending = try context.fetch(d) }
        catch { NSLog("Kaste: backfillSearchKey fetch failed: \(error)"); return }
        guard !pending.isEmpty else { return }
        for item in pending { item.searchKey = item.plainText?.lowercased() }
        do { try context.save() }
        catch { NSLog("Kaste: backfillSearchKey save failed: \(error)"); context.rollback() }
    }

    /// Seed `sortRank` for rows that predate the drag-to-reorder feature.
    /// Uses `lastUsedAt` so the initial visible order after upgrade matches
    /// what the user was seeing before.
    func backfillSortRank() {
        let d = FetchDescriptor<ClipItem>(predicate: #Predicate { $0.sortRank == 0 })
        let pending: [ClipItem]
        do { pending = try context.fetch(d) }
        catch { NSLog("Kaste: backfillSortRank fetch failed: \(error)"); return }
        guard !pending.isEmpty else { return }
        for item in pending {
            item.sortRank = item.lastUsedAt.timeIntervalSince1970
        }
        do { try context.save() }
        catch { NSLog("Kaste: backfillSortRank save failed: \(error)"); context.rollback() }
    }

    func enforceRetention() {
        let days = UserDefaults.standard.object(forKey: "retentionDays") as? Int ?? 30
        guard days > 0 else { return }
        let cutoff = Date().addingTimeInterval(-Double(days) * 86400)
        let expired = FetchDescriptor<ClipItem>(
            predicate: #Predicate { !$0.isPinned && $0.lastUsedAt < cutoff }
        )
        let victims: [ClipItem]
        do { victims = try context.fetch(expired) }
        catch { NSLog("Kaste: enforceRetention fetch failed: \(error)"); return }
        guard !victims.isEmpty else { return }
        for item in victims {
            ClipImageCache.drop(item.id)
            context.delete(item)
        }
        do { try context.save() }
        catch { NSLog("Kaste: enforceRetention save failed: \(error)"); context.rollback() }
    }

    func enforceCapacity() {
        let maxItems = UserDefaults.standard.object(forKey: "maxItems") as? Int ?? 1000
        let nonPinned = FetchDescriptor<ClipItem>(predicate: #Predicate { !$0.isPinned })
        let total: Int
        do { total = try context.fetchCount(nonPinned) }
        catch { NSLog("Kaste: enforceCapacity count failed: \(error)"); return }
        guard total > maxItems else { return }
        var oldest = FetchDescriptor<ClipItem>(
            predicate: #Predicate { !$0.isPinned },
            sortBy: [SortDescriptor(\.lastUsedAt, order: .forward)]
        )
        oldest.fetchLimit = total - maxItems
        let victims: [ClipItem]
        do { victims = try context.fetch(oldest) }
        catch { NSLog("Kaste: enforceCapacity fetch failed: \(error)"); return }
        for item in victims {
            ClipImageCache.drop(item.id)
            context.delete(item)
        }
        do { try context.save() }
        catch { NSLog("Kaste: enforceCapacity save failed: \(error)"); context.rollback() }
    }

    private func serialize() -> Data? {
        guard let items = pasteboard.pasteboardItems else { return nil }
        var dict: [[String: Data]] = []
        for item in items {
            var entry: [String: Data] = [:]
            for type in item.types {
                if let data = item.data(forType: type) {
                    entry[type.rawValue] = data
                }
            }
            dict.append(entry)
        }
        return try? NSKeyedArchiver.archivedData(withRootObject: dict, requiringSecureCoding: false)
    }

    private func sha256(_ s: String) -> String { sha256(Data(s.utf8)) }
    private func sha256(_ data: Data) -> String {
        SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
    }

    /// Multi-strategy extraction of an image from HTML / WebArchive / RTF /
    /// URL-list representations. Chrome extensions typically write one of
    /// these instead of a raw image type. Everything is normalized to PNG.
    private func extractImagePNGFromRichPasteboard() -> Data? {
        let sources: [(String, () -> String?)] = [
            (".html",     { self.pasteboard.data(forType: .html).flatMap { self.decodeText($0) } }),
            ("webarchive", { self.webarchiveText() }),
            ("uri-list",  { self.pasteboard.string(forType: NSPasteboard.PasteboardType("public.utf8-plain-text")) }),
            (".string",   { self.pasteboard.string(forType: .string) })
        ]
        for (label, fetch) in sources {
            guard let text = fetch(), !text.isEmpty else { continue }
            if let png = Self.extractDataURIImagePNG(from: text) {
                NSLog("Kaste: extracted embedded image via \(label) (\(png.count) bytes)")
                return png
            }
        }
        return nil
    }

    /// Try several encodings — Chrome sometimes writes UTF-16 for HTML.
    private func decodeText(_ data: Data) -> String? {
        for enc in [String.Encoding.utf8, .utf16, .utf16LittleEndian, .utf16BigEndian, .isoLatin1] {
            if let s = String(data: data, encoding: enc), !s.isEmpty { return s }
        }
        return nil
    }

    /// Deserialize a `com.apple.webarchive` blob and pull its dominant HTML
    /// resource (the main frame's content) for data-URI scanning.
    private func webarchiveText() -> String? {
        guard let data = pasteboard.data(forType: NSPasteboard.PasteboardType("com.apple.webarchive")),
              let plist = try? PropertyListSerialization.propertyList(from: data, options: [], format: nil) as? [String: Any],
              let mainResource = plist["WebMainResource"] as? [String: Any],
              let bodyData = mainResource["WebResourceData"] as? Data else {
            return nil
        }
        return decodeText(bodyData)
    }

    /// Scans arbitrary text for the first `data:image/*;base64,…` payload
    /// (surrounded by `"`, `'`, `)`, whitespace, or end-of-string) and
    /// returns a PNG-encoded copy. Loose enough to cover HTML `<img src>`,
    /// CSS `background:url(...)`, WebArchive resources, and plain text.
    static func extractDataURIImagePNG(from text: String) -> Data? {
        let pattern = #"data:image/([a-zA-Z0-9+.\-]+);base64,([A-Za-z0-9+/=\s]+?)(?=[\"'\)\s<>]|$)"#
        guard let regex = try? NSRegularExpression(pattern: pattern,
                                                   options: [.caseInsensitive, .dotMatchesLineSeparators]) else {
            NSLog("Kaste: data-URI regex compile failed")
            return nil
        }
        let range = NSRange(text.startIndex..., in: text)
        guard let match = regex.firstMatch(in: text, options: [], range: range),
              match.numberOfRanges >= 3,
              let mimeRange = Range(match.range(at: 1), in: text),
              let base64Range = Range(match.range(at: 2), in: text) else {
            NSLog("Kaste: no data:image/*;base64 pattern found (text \(text.count) chars)")
            return nil
        }
        let mime = String(text[mimeRange]).lowercased()
        // Strip whitespace injected by HTML wrapping / pretty printing before decode.
        let base64 = String(text[base64Range])
            .components(separatedBy: .whitespacesAndNewlines)
            .joined()
        guard let raw = Data(base64Encoded: base64, options: [.ignoreUnknownCharacters]) else {
            NSLog("Kaste: base64 decode failed (payload \(base64.count) chars, mime=\(mime))")
            return nil
        }
        if mime.contains("png") {
            // Already PNG; skip the tiff round-trip and just verify NSImage can load it.
            if NSImage(data: raw) != nil { return raw }
        }
        guard let img = NSImage(data: raw) else {
            NSLog("Kaste: NSImage(data:) failed after base64 decode (raw \(raw.count) bytes, mime=\(mime))")
            return nil
        }
        guard let tiff = img.tiffRepresentation,
              let rep = NSBitmapImageRep(data: tiff),
              let png = rep.representation(using: .png, properties: [:]) else {
            NSLog("Kaste: PNG re-encode failed (mime=\(mime))")
            return nil
        }
        return png
    }
}
